#!/bin/bash

echo 'make dir'

mkdir file1 file2
rsync file1 file2
rsync -a --delete file1
rsync -a file1

echo 'make user'
useradd -e /usr/sbin/user $5
echo 'make password'
passwd $5

echo 'delete file1 file2'
rmdir file1 file2

echo 'check if it gone'
ls -l
